[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
egui = "0.33"
bevy_egui = { git = "https://github.com/theinfinityglitch/bevy_egui.git", branch = "bevy-0.17.2", default-features = false, features = [
    "manage_clipboard",
    "default_fonts",
    "render",
    "bevy_ui"
] }
